<?php

/**
 * Daftar siswa XI TKJ 3 untuk website HTML.
 * Seeder Laravel utama berada di:
 * D:\laragon\www\kelas-tkj\database\seeders\DatabaseSeeder.php
 */

return [
    1 => 'IVAN RACHMAD ADITYA',
    2 => 'MUKHAMMAD AZRIL ANSORI',
    3 => "MUKHAMMAD ROBITH SYAHRUL SYA'BANA",
    4 => 'NOVIA DWI ARIANI',
    5 => 'NUR HANIF ROBBYANZA',
    6 => 'NUR SYFAUL LATHIFAH',
    7 => 'NURUL LAILATUL AHAIDIAH',
    8 => 'NURUL QOIDATUR ROHMAH',
    9 => 'PUTRI FEBRIANTI',
    10 => 'QWYNZA DYANDRA PUTRI ALLANA',
    11 => 'RACHEL AMALIA PUTRI WIBOWO',
    12 => 'RAFA DWI PUTRA ANANTA',
    13 => 'RASYA PRATAMA PUTRA RACHMAN',
    14 => 'RAYENDRA FAREL MAHRUZ AL FAREZA',
    15 => 'REIHANA TSABITA QOLBY',
    16 => 'RENYTA MEI PUSPITA PUTRI',
    17 => 'RIDHO ARDIANSYAH PRATAMA',
    18 => 'RIDLO MAULANA WAHYUDI',
    19 => 'RIZKY ADI DERMAWAN',
    20 => 'RIZKY ALIF MAULANA',
    21 => 'SABRINA DELAROSA',
    22 => 'SAFIN AGIM NASTIAR',
    23 => 'SAMIR NASRI',
    24 => 'SEFRIL FITRIA RAMADANI',
    25 => 'SHEVAZELDA ERLANGGA',
    26 => 'SIFA ROMADHONIA',
    27 => 'SITI SAFRINA INDAH YANI',
    28 => 'SONY BRILLIANT ERLANDO',
    29 => 'SYAFAAT HIDAYATULLOH',
    30 => 'ULYATUL MURTASYIDAH',
    31 => 'VENNA MELINDA',
    32 => 'YONATAN ABNER NUSANTARA',
    33 => 'ZAEN ADITYA WAHYU PRATAMA',
    34 => 'ZAZA NUR RAHMA',
];
